###Test
GET http://localhost:3001/api/test

###Get all amenities
GET http://localhost:3002/api/amenities

###Get Amenities for a specific listing
GET http://localhost:3002/api/amenities/1


###Get location
GET http://localhost:4000/api/location

###Get location
GET http://localhost:4000/api/location/description

###Get a description for one property
GET http://localhost:3050/api/about/2


###Get images to display in gallery
GET http://localhost:3010/api/gallery


###Get users first and last name 
GET http://localhost:4001/api/users/1

###Get host info
GET http://localhost:4001/api/hosts/about/1

###Get reviews
GET http://localhost:3005/api/reviews

